// frontend-angular/src/app/components/detalle-juego/detalle-juego.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { JuegoService } from '../../services/juego.service';

@Component({
  selector: 'app-detalle-juego',
  templateUrl: './detalle-juego.component.html',
  styleUrls: ['./detalle-juego.component.scss']
})
export class DetalleJuegoComponent implements OnInit {
  juego: any = null;
  cargando: boolean = false;
  error: string = '';
  mostrarImagenPorDefecto: boolean = false;

  constructor(
    private juegoService: JuegoService,
    private route: ActivatedRoute,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      if (params['id']) {
        this.cargarJuego(params['id']);
      }
    });
  }

  cargarJuego(id: string): void {
    this.cargando = true;
    this.error = '';

    this.juegoService.obtenerJuegoPorId(id)
      .subscribe({
        next: (data) => {
          this.juego = data;
          this.cargando = false;
        },
        error: (err) => {
          this.error = 'Error al cargar el juego: ' + (err.error?.mensaje || err.message);
          this.cargando = false;
        }
      });
  }

  editarJuego(): void {
    this.router.navigate(['/editar', this.juego._id]);
  }

  volver(): void {
    this.router.navigate(['/lista']);
  }

  formatearFecha(fecha: any): string {
    return new Date(fecha).toLocaleDateString('es-ES', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  }
}

<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <!-- Loader -->
      <div *ngIf="cargando" class="text-center my-5">
        <div class="spinner-border text-primary" role="status">
          <span class="visually-hidden">Cargando...</span>
        </div>
        <p class="mt-2">Cargando detalle del juego...</p>
      </div>

      <!-- Error -->
      <div *ngIf="error && !cargando" class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ error }}
      </div>

      <!-- Detalle del juego -->
      <div *ngIf="juego && !cargando" class="card">
      <!-- Imagen -->
      <div *ngIf="juego.imagen && juego.imagen.trim() !== ''" class="card-img-top position-relative" style="height: 300px; overflow: hidden; background: #f0f0f0;">
        <img 
          [src]="juego.imagen" 
          alt="{{ juego.titulo }}" 
          class="w-100 h-100"
          style="object-fit: cover; object-position: center;"
          (error)="mostrarImagenPorDefecto = true"
        />
      </div>
      <div *ngIf="!juego.imagen || juego.imagen.trim() === '' || mostrarImagenPorDefecto" class="card-img-top bg-secondary" style="height: 300px; display: flex; align-items: center; justify-content: center;">
        <span class="text-white display-4">🎮</span>
      </div>

        <div class="card-body">
          <!-- Título -->
          <h1 class="card-title mb-2">{{ juego.titulo }}</h1>

          <!-- Badges de estado -->
          <div class="mb-3">
            <span *ngIf="juego.completado" class="badge bg-success me-2">✅ Completado</span>
            <span *ngIf="!juego.completado" class="badge bg-warning text-dark me-2">⏳ En progreso</span>
            <span class="badge bg-info">📅 {{ formatearFecha(juego.fechaLanzamiento) }}</span>
          </div>

          <!-- Descripción -->
          <p class="card-text text-muted mb-4">{{ juego.descripcion }}</p>

          <!-- Información detallada -->
          <div class="row mb-4">
            <div class="col-md-6">
              <h5 class="mb-3">📊 Información</h5>
              <div class="info-item mb-3">
                <strong>Horas jugadas:</strong>
                <p class="mb-0">{{ juego.horasJugadas }} horas</p>
              </div>
              <div class="info-item mb-3">
                <strong>Progreso:</strong>
                <p class="mb-0">{{ juego.porcentajeCompletado }}%</p>
              </div>
            </div>

            <div class="col-md-6">
              <h5 class="mb-3">📈 Estadísticas</h5>
              <div class="info-item mb-3">
                <strong>Creado:</strong>
                <p class="mb-0">{{ formatearFecha(juego.createdAt) }}</p>
              </div>
              <div class="info-item mb-3">
                <strong>Última actualización:</strong>
                <p class="mb-0">{{ formatearFecha(juego.updatedAt) }}</p>
              </div>
            </div>
          </div>

          <!-- Barra de progreso -->
          <div class="mb-4">
            <h5 class="mb-2">Barra de Progreso</h5>
            <div class="progress" style="height: 30px;">
              <div 
                class="progress-bar bg-success" 
                role="progressbar"
                [style.width.%]="juego.porcentajeCompletado"
              >
                <strong>{{ juego.porcentajeCompletado }}%</strong>
              </div>
            </div>
          </div>

          <!-- Botones -->
          <div class="d-grid gap-2 d-md-flex justify-content-md-between">
            <button type="button" class="btn btn-secondary" (click)="volver()">
              ← Volver a la lista
            </button>
            <button type="button" class="btn btn-primary" (click)="editarJuego()">
              ✏️ Editar juego
            </button>
          </div>
        </div>
      </div>

      <!-- Sin datos -->
      <div *ngIf="!juego && !cargando && !error" class="alert alert-info">
        No se encontró el juego solicitado.
      </div>
    </div>
  </div>
</div>

// frontend-react/src/components/DetalleJuego/DetalleJuego.jsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { juegoService } from '../../services/juegoService';
import './DetalleJuego.css';

const DetalleJuego = () => {
  const [juego, setJuego] = useState(null);
  const [cargando, setCargando] = useState(false);
  const [error, setError] = useState('');
  const [mostrarImagenPorDefecto, setMostrarImagenPorDefecto] = useState(false);
  const { id } = useParams();
  const navigate = useNavigate();

  useEffect(() => {
    cargarJuego();
  }, [id]);

  const cargarJuego = async () => {
    setCargando(true);
    setError('');

    try {
      const data = await juegoService.obtenerJuegoPorId(id);
      setJuego(data);
    } catch (err) {
      setError('Error al cargar el juego: ' + (err.mensaje || err.message));
    } finally {
      setCargando(false);
    }
  };

  const formatearFecha = (fecha) => {
    return new Date(fecha).toLocaleDateString('es-ES', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  const handleImagenError = () => {
    setMostrarImagenPorDefecto(true);
  };

  const editarJuego = () => {
    navigate(`/editar/${juego._id}`);
  };

  const volver = () => {
    navigate('/lista');
  };

  if (cargando) {
    return (
      <div className="container my-5">
        <div className="text-center my-5">
          <div className="spinner-border text-primary" role="status">
            <span className="visually-hidden">Cargando...</span>
          </div>
          <p className="mt-2">Cargando detalle del juego...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="container my-5">
        <div className="alert alert-danger alert-dismissible fade show" role="alert">
          {error}
        </div>
      </div>
    );
  }

  if (!juego) {
    return (
      <div className="container my-5">
        <div className="alert alert-info">No se encontró el juego solicitado.</div>
      </div>
    );
  }

  return (
    <div className="container my-5">
      <div className="row justify-content-center">
        <div className="col-md-8">
          <div className="card">
            {/* Imagen */}
            <div
              className="card-img-top position-relative"
              style={{
                height: '300px',
                overflow: 'hidden',
                background: '#f0f0f0'
              }}
            >
              {!mostrarImagenPorDefecto && juego.imagen && juego.imagen.trim() !== '' ? (
                <img
                  src={juego.imagen}
                  alt={juego.titulo}
                  className="w-100 h-100"
                  style={{
                    objectFit: 'cover',
                    objectPosition: 'center'
                  }}
                  onError={handleImagenError}
                />
              ) : (
                <div
                  style={{
                    height: '100%',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    backgroundColor: '#6c757d'
                  }}
                >
                  <span style={{ fontSize: '3rem' }}>🎮</span>
                </div>
              )}
            </div>

            <div className="card-body">
              {/* Título */}
              <h1 className="card-title mb-2">{juego.titulo}</h1>

              {/* Badges de estado */}
              <div className="mb-3">
                {(() => {
                const estaCompletado = juego.completado || juego.porcentajeCompletado === 100;
                return estaCompletado ? (
                  <span className="badge bg-success me-2">✅ Completado</span>
                ) : (
                  <span className="badge bg-warning text-dark me-2">⏳ En progreso</span>
                );
              })()}
                <span className="badge bg-info">📅 {formatearFecha(juego.fechaLanzamiento)}</span>
              </div>

              {/* Descripción */}
              <p className="card-text text-muted mb-4">{juego.descripcion}</p>

              {/* Información detallada */}
              <div className="row mb-4">
                <div className="col-md-6">
                  <h5 className="mb-3">📊 Información</h5>
                  <div className="info-item mb-3">
                    <strong>Horas jugadas:</strong>
                    <p className="mb-0">{juego.horasJugadas} horas</p>
                  </div>
                  <div className="info-item mb-3">
                    <strong>Progreso:</strong>
                    <p className="mb-0">{juego.porcentajeCompletado}%</p>
                  </div>
                </div>

                <div className="col-md-6">
                  <h5 className="mb-3">📈 Estadísticas</h5>
                  <div className="info-item mb-3">
                    <strong>Creado:</strong>
                    <p className="mb-0">{formatearFecha(juego.createdAt)}</p>
                  </div>
                  <div className="info-item mb-3">
                    <strong>Última actualización:</strong>
                    <p className="mb-0">{formatearFecha(juego.updatedAt)}</p>
                  </div>
                </div>
              </div>

              {/* Barra de progreso */}
              <div className="mb-4">
                <h5 className="mb-2">Barra de Progreso</h5>
                <div className="progress" style={{ height: '30px' }}>
                  <div
                    className="progress-bar bg-success"
                    role="progressbar"
                    style={{ width: `${juego.porcentajeCompletado}%` }}
                  >
                    <strong>{juego.porcentajeCompletado}%</strong>
                  </div>
                </div>
              </div>

              {/* Botones */}
              <div className="d-grid gap-2 d-md-flex justify-content-md-between">
                <button type="button" className="btn btn-secondary" onClick={volver}>
                  ← Volver a la lista
                </button>
                <button type="button" className="btn btn-primary" onClick={editarJuego}>
                  ✏️ Editar juego
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DetalleJuego;
