// frontend-react/src/components/FormularioJuego/FormularioJuego.jsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { juegoService } from '../../services/juegoService';
import './FormularioJuego.css';

const FormularioJuego = () => {
  const [formData, setFormData] = useState({
    titulo: '',
    descripcion: '',
    horasJugadas: 0,
    fechaLanzamiento: '',
    completado: false,
    porcentajeCompletado: 0,
    imagen: ''
  });

  const [errores, setErrores] = useState({});
  const [cargando, setCargando] = useState(false);
  const [error, setError] = useState('');
  const [previewError, setPreviewError] = useState(false);
  const [exitoMensaje, setExitoMensaje] = useState('');
  const [editando, setEditando] = useState(false);
  const { id } = useParams();
  const navigate = useNavigate();

  useEffect(() => {
    if (id) {
      setEditando(true);
      cargarJuego();
    }
  }, [id]);

  const cargarJuego = async () => {
    setCargando(true);
    try {
      const juego = await juegoService.obtenerJuegoPorId(id);
      const fechaLanzamiento = juego.fechaLanzamiento
        ? new Date(juego.fechaLanzamiento).toISOString().split('T')[0]
        : '';

      // si el porcentaje viene en 100 también marcamos como completado para evitar discrepancias
      const completadoReal = juego.completado || juego.porcentajeCompletado === 100;

      setFormData({
        titulo: juego.titulo,
        descripcion: juego.descripcion,
        horasJugadas: juego.horasJugadas,
        fechaLanzamiento: fechaLanzamiento,
        completado: completadoReal,
        porcentajeCompletado: juego.porcentajeCompletado,
        imagen: juego.imagen || ''
      });
    } catch (err) {
      setError('Error al cargar el juego: ' + (err.mensaje || err.message));
    } finally {
      setCargando(false);
    }
  };

  const validarFormulario = () => {
    const nuevosErrores = {};

    if (!formData.titulo || formData.titulo.trim().length < 3) {
      nuevosErrores.titulo = 'El título debe tener al menos 3 caracteres';
    }

    if (!formData.descripcion || formData.descripcion.trim().length < 10) {
      nuevosErrores.descripcion = 'La descripción debe tener al menos 10 caracteres';
    }

    if (!formData.fechaLanzamiento) {
      nuevosErrores.fechaLanzamiento = 'La fecha de lanzamiento es obligatoria';
    }

    if (formData.horasJugadas < 0 || formData.horasJugadas > 100000) {
      nuevosErrores.horasJugadas = 'Las horas deben estar entre 0 y 100000';
    }

    if (formData.porcentajeCompletado < 0 || formData.porcentajeCompletado > 100) {
      nuevosErrores.porcentajeCompletado = 'El porcentaje debe estar entre 0 y 100';
    }

    setErrores(nuevosErrores);
    return Object.keys(nuevosErrores).length === 0;
  };

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;

    // when the percentage slider changes we also adjust the "completado" flag
    if (name === 'porcentajeCompletado') {
      const porcentaje = Number(value);
      setFormData(prev => ({
        ...prev,
        porcentajeCompletado: porcentaje,
        completado: porcentaje === 100
      }));
      return;
    }

    // when the user toggles the checkbox we may want to bump the percentage up to 100
    if (name === 'completado') {
      const checkedVal = checked;
      setFormData(prev => ({
        ...prev,
        completado: checkedVal,
        // if the box is checked make sure the progress is full, otherwise leave the existing value alone
        porcentajeCompletado: checkedVal ? 100 : prev.porcentajeCompletado
      }));
      return;
    }

    // default handler for other fields
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox'
        ? checked
        : type === 'number'
          ? Number(value)
          : value
    }));
    if (name === 'imagen') {
      setPreviewError(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();

    if (!validarFormulario()) {
      return;
    }

    setCargando(true);
    setError('');
    setExitoMensaje('');

    try {
      if (editando) {
        await juegoService.actualizarJuego(id, formData);
        setExitoMensaje('Juego actualizado exitosamente');
      } else {
        await juegoService.crearJuego(formData);
        setExitoMensaje('Juego creado exitosamente');
      }

      setTimeout(() => navigate('/lista'), 2000);
    } catch (err) {
      setError('Error al guardar: ' + (err.mensaje || err.message));
    } finally {
      setCargando(false);
    }
  };

  const cancelar = () => {
    navigate('/lista');
  };

  return (
    <div className="container my-5">
      <div className="row justify-content-center">
        <div className="col-md-8">
          <div className="card">
            <div className="card-header bg-primary text-white">
              <h2 className="mb-0">
                {editando ? '✏️ Editar Juego' : '➕ Nuevo Juego'}
              </h2>
            </div>

            <div className="card-body">
              {/* Alertas */}
              {exitoMensaje && (
                <div className="alert alert-success alert-dismissible fade show" role="alert">
                  {exitoMensaje}
                </div>
              )}

              {error && (
                <div className="alert alert-danger alert-dismissible fade show" role="alert">
                  {error}
                  <button
                    type="button"
                    className="btn-close"
                    onClick={() => setError('')}
                  ></button>
                </div>
              )}

              {/* Loader */}
              {cargando && (
                <div className="text-center my-4">
                  <div className="spinner-border text-primary" role="status">
                    <span className="visually-hidden">Cargando...</span>
                  </div>
                </div>
              )}

              {/* Formulario */}
              {!cargando && (
                <form onSubmit={handleSubmit}>
                  {/* Título */}
                  <div className="mb-3">
                    <label htmlFor="titulo" className="form-label">
                      Título del Juego *
                    </label>
                    <input
                      type="text"
                      className={`form-control ${errores.titulo ? 'is-invalid' : ''}`}
                      id="titulo"
                      name="titulo"
                      value={formData.titulo}
                      onChange={handleChange}
                      placeholder="Ej: The Legend of Zelda"
                    />
                    {errores.titulo && (
                      <div className="invalid-feedback">{errores.titulo}</div>
                    )}
                  </div>

                  {/* Descripción */}
                  <div className="mb-3">
                    <label htmlFor="descripcion" className="form-label">
                      Descripción *
                    </label>
                    <textarea
                      className={`form-control ${errores.descripcion ? 'is-invalid' : ''}`}
                      id="descripcion"
                      name="descripcion"
                      rows="4"
                      value={formData.descripcion}
                      onChange={handleChange}
                      placeholder="Describe el juego..."
                    ></textarea>
                    {errores.descripcion && (
                      <div className="invalid-feedback">{errores.descripcion}</div>
                    )}
                  </div>

                  {/* Fecha de lanzamiento */}
                  <div className="mb-3">
                    <label htmlFor="fechaLanzamiento" className="form-label">
                      Fecha de Lanzamiento *
                    </label>
                    <input
                      type="date"
                      className={`form-control ${errores.fechaLanzamiento ? 'is-invalid' : ''}`}
                      id="fechaLanzamiento"
                      name="fechaLanzamiento"
                      value={formData.fechaLanzamiento}
                      onChange={handleChange}
                    />
                    {errores.fechaLanzamiento && (
                      <div className="invalid-feedback">{errores.fechaLanzamiento}</div>
                    )}
                  </div>

                  {/* Horas Jugadas */}
                  <div className="mb-3">
                    <label htmlFor="horasJugadas" className="form-label">
                      Horas Jugadas *
                    </label>
                    <input
                      type="number"
                      className={`form-control ${errores.horasJugadas ? 'is-invalid' : ''}`}
                      id="horasJugadas"
                      name="horasJugadas"
                      min="0"
                      max="100000"
                      value={formData.horasJugadas}
                      onChange={handleChange}
                    />
                    {errores.horasJugadas && (
                      <div className="invalid-feedback">{errores.horasJugadas}</div>
                    )}
                  </div>

                  {/* Porcentaje de completado */}
                  <div className="mb-3">
                    <label htmlFor="porcentaje" className="form-label">
                      Porcentaje de Completado: {formData.porcentajeCompletado}%
                    </label>
                    <input
                      type="range"
                      className="form-range"
                      id="porcentaje"
                      name="porcentajeCompletado"
                      min="0"
                      max="100"
                      value={formData.porcentajeCompletado}
                      onChange={handleChange}
                    />
                    <div className="progress mt-2">
                      <div
                        className="progress-bar bg-success"
                        role="progressbar"
                        style={{ width: `${formData.porcentajeCompletado}%` }}
                      ></div>
                    </div>
                    {formData.porcentajeCompletado !== 100 && (
                      <small className="text-muted text-danger">
                        El juego sólo puede completarse cuando el porcentaje llega a 100%.
                      </small>
                    )}
                  </div>

                  {/* Completado */}
                  <div className="mb-3 form-check">
                    <input
                      type="checkbox"
                      className="form-check-input"
                      id="completado"
                      name="completado"
                      checked={formData.completado}
                      onChange={handleChange}
                      disabled={formData.porcentajeCompletado !== 100}
                    />
                    <label className="form-check-label" htmlFor="completado">
                      ✅ Juego completado
                    </label>
                  </div>

                  {/* Imagen URL */}
                  <div className="mb-3">
                    <label htmlFor="imagen" className="form-label">
                      URL de la Imagen
                    </label>
                    <div className="d-flex align-items-center gap-3">
                      <input
                        type="url"
                        className="form-control"
                        id="imagen"
                        name="imagen"
                        value={formData.imagen}
                        onChange={handleChange}
                        placeholder="https://..."
                      />
                      <div style={{ width: 80, height: 80, border: '1px solid #ddd', borderRadius: 6, overflow: 'hidden', background: '#f8f9fa' }}>
                        {formData.imagen ? (
                          <a href={formData.imagen} target="_blank" rel="noreferrer">
                            <img
                              src={formData.imagen}
                              alt="preview"
                              style={{ width: '100%', height: '100%', objectFit: 'cover', display: previewError ? 'none' : 'block' }}
                              onError={() => setPreviewError(true)}
                            />
                          </a>
                        ) : (
                          <div className="text-center text-muted" style={{ fontSize: 12, paddingTop: 26 }}>Previsual.</div>
                        )}
                        {previewError && (
                          <div className="text-center text-muted" style={{ fontSize: 10, padding: 6 }}>URL inválida</div>
                        )}
                      </div>
                    </div>
                  </div>

                  {/* Botones */}
                  <div className="d-grid gap-2 d-md-flex justify-content-md-end">
                    <button type="button" className="btn btn-secondary" onClick={cancelar}>
                      ❌ Cancelar
                    </button>
                    <button type="submit" className="btn btn-primary" disabled={cargando}>
                      💾 {editando ? 'Actualizar' : 'Crear'}
                    </button>
                  </div>
                </form>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FormularioJuego;

// frontend-angular/src/app/components/formulario-juego/formulario-juego.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { JuegoService } from '../../services/juego.service';

@Component({
  selector: 'app-formulario-juego',
  templateUrl: './formulario-juego.component.html',
  styleUrls: ['./formulario-juego.component.scss']
})
export class FormularioJuegoComponent implements OnInit {
  formulario!: FormGroup;
  cargando: boolean = false;
  error: string = '';
  exitoMensaje: string = '';
  editando: boolean = false;
  juegoId: string = '';
  previewUrl: string = '';
  previewError: boolean = false;

  constructor(
    private fb: FormBuilder,
    private juegoService: JuegoService,
    private route: ActivatedRoute,
    private router: Router
  ) {
    this.crearFormulario();
  }

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      if (params['id']) {
        this.editando = true;
        this.juegoId = params['id'];
        this.cargarJuego();
      }
    });
  }

  crearFormulario(): void {
    this.formulario = this.fb.group({
      titulo: ['', [Validators.required, Validators.minLength(3)]],
      descripcion: ['', [Validators.required, Validators.minLength(10)]],
      horasJugadas: [0, [Validators.required, Validators.min(0), Validators.max(100000)]],
      fechaLanzamiento: ['', Validators.required],
      completado: [false],
      porcentajeCompletado: [0, [Validators.required, Validators.min(0), Validators.max(100)]],
      imagen: ['']
    });

    // observar cambios en el campo imagen para actualizar la vista previa
    this.formulario.get('imagen')?.valueChanges.subscribe((val: string) => {
      this.previewError = false;
      this.previewUrl = val || '';
    });
  }

  cargarJuego(): void {
    this.cargando = true;
    this.juegoService.obtenerJuegoPorId(this.juegoId)
      .subscribe({
        next: (juego) => {
          // Convertir fecha al formato esperado
          const fechaLanzamiento = juego.fechaLanzamiento 
            ? new Date(juego.fechaLanzamiento).toISOString().split('T')[0] 
            : '';

          this.formulario.patchValue({
            titulo: juego.titulo,
            descripcion: juego.descripcion,
            horasJugadas: juego.horasJugadas,
            fechaLanzamiento: fechaLanzamiento,
            completado: juego.completado,
            porcentajeCompletado: juego.porcentajeCompletado,
            imagen: juego.imagen
          });
          this.previewUrl = juego.imagen || '';
          this.cargando = false;
        },
        error: (err) => {
          this.error = 'Error al cargar el juego: ' + (err.error?.mensaje || err.message);
          this.cargando = false;
        }
      });
  }

  guardar(): void {
    if (this.formulario.invalid) {
      this.error = 'Por favor, complete todos los campos correctamente';
      return;
    }

    this.cargando = true;
    this.error = '';
    this.exitoMensaje = '';

    const datos = this.formulario.value;

    if (this.editando) {
      this.juegoService.actualizarJuego(this.juegoId, datos)
        .subscribe({
          next: () => {
            this.exitoMensaje = 'Juego actualizado exitosamente';
            setTimeout(() => this.router.navigate(['/lista']), 2000);
          },
          error: (err) => {
            this.error = 'Error al actualizar: ' + (err.error?.mensaje || err.message);
            this.cargando = false;
          }
        });
    } else {
      this.juegoService.crearJuego(datos)
        .subscribe({
          next: () => {
            this.exitoMensaje = 'Juego creado exitosamente';
            setTimeout(() => this.router.navigate(['/lista']), 2000);
          },
          error: (err) => {
            this.error = 'Error al crear: ' + (err.error?.mensaje || err.message);
            this.cargando = false;
          }
        });
    }
  }

  cancelar(): void {
    this.router.navigate(['/lista']);
  }

  get titulo() {
    return this.formulario.get('titulo');
  }

  get descripcion() {
    return this.formulario.get('descripcion');
  }

  get horasJugadas() {
    return this.formulario.get('horasJugadas');
  }

  get fechaLanzamiento() {
    return this.formulario.get('fechaLanzamiento');
  }

  get porcentajeCompletado() {
    return this.formulario.get('porcentajeCompletado');
  }

  actualizarPorcentaje(valor: number): void {
    this.formulario.patchValue({ porcentajeCompletado: valor });
  }
}

<div class="container my-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header bg-primary text-white">
          <h2 class="mb-0">{{ editando ? '✏️ Editar Juego' : '➕ Nuevo Juego' }}</h2>
        </div>
        <div class="card-body">
          <!-- Alertas -->
          <div *ngIf="exitoMensaje" class="alert alert-success alert-dismissible fade show" role="alert">
            {{ exitoMensaje }}
          </div>

          <div *ngIf="error" class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ error }}
            <button type="button" class="btn-close" (click)="error = ''"></button>
          </div>

          <!-- Loader -->
          <div *ngIf="cargando" class="text-center my-4">
            <div class="spinner-border text-primary" role="status">
              <span class="visually-hidden">Cargando...</span>
            </div>
          </div>

          <!-- Formulario -->
          <form [formGroup]="formulario" (ngSubmit)="guardar()" *ngIf="!cargando" class="form">
            <!-- Título -->
            <div class="mb-3">
              <label for="titulo" class="form-label">Título del Juego *</label>
              <input 
                type="text" 
                class="form-control" 
                id="titulo"
                formControlName="titulo"
                [class.is-invalid]="titulo?.invalid && titulo?.touched"
                placeholder="Ej: The Legend of Zelda"
              />
              <div class="invalid-feedback" *ngIf="titulo?.invalid && titulo?.touched">
                <div *ngIf="titulo?.errors?.['required']">El título es obligatorio</div>
                <div *ngIf="titulo?.errors?.['minlength']">Mínimo 3 caracteres</div>
              </div>
            </div>

            <!-- Descripción -->
            <div class="mb-3">
              <label for="descripcion" class="form-label">Descripción *</label>
              <textarea 
                class="form-control" 
                id="descripcion"
                formControlName="descripcion"
                rows="4"
                [class.is-invalid]="descripcion?.invalid && descripcion?.touched"
                placeholder="Describe el juego..."
              ></textarea>
              <div class="invalid-feedback" *ngIf="descripcion?.invalid && descripcion?.touched">
                <div *ngIf="descripcion?.errors?.['required']">La descripción es obligatoria</div>
                <div *ngIf="descripcion?.errors?.['minlength']">Mínimo 10 caracteres</div>
              </div>
            </div>

            <!-- Fecha de lanzamiento -->
            <div class="mb-3">
              <label for="fechaLanzamiento" class="form-label">Fecha de Lanzamiento *</label>
              <input 
                type="date" 
                class="form-control" 
                id="fechaLanzamiento"
                formControlName="fechaLanzamiento"
                [class.is-invalid]="fechaLanzamiento?.invalid && fechaLanzamiento?.touched"
              />
              <div class="invalid-feedback" *ngIf="fechaLanzamiento?.invalid && fechaLanzamiento?.touched">
                La fecha es obligatoria
              </div>
            </div>

            <!-- Horas Jugadas -->
            <div class="mb-3">
              <label for="horasJugadas" class="form-label">Horas Jugadas *</label>
              <input 
                type="number" 
                class="form-control" 
                id="horasJugadas"
                formControlName="horasJugadas"
                min="0"
                max="100000"
                [class.is-invalid]="horasJugadas?.invalid && horasJugadas?.touched"
              />
              <div class="invalid-feedback" *ngIf="horasJugadas?.invalid && horasJugadas?.touched">
                <div *ngIf="horasJugadas?.errors?.['required']">Las horas jugadas son obligatorias</div>
                <div *ngIf="horasJugadas?.errors?.['min']">No pueden ser negativas</div>
                <div *ngIf="horasJugadas?.errors?.['max']">Máximo 100000 horas</div>
              </div>
            </div>

            <!-- Porcentaje de completado -->
            <div class="mb-3">
              <label for="porcentaje" class="form-label">Porcentaje de Completado: {{ porcentajeCompletado?.value }}%</label>
              <input 
                type="range" 
                class="form-range" 
                id="porcentaje"
                formControlName="porcentajeCompletado"
                min="0"
                max="100"
                (change)="actualizarPorcentaje($any($event.target).value)"
              />
              <div class="progress mt-2">
                <div 
                  class="progress-bar bg-success" 
                  role="progressbar"
                  [style.width.%]="porcentajeCompletado?.value"
                ></div>
              </div>
            </div>

            <!-- Completado -->
            <div class="mb-3 form-check">
              <input 
                type="checkbox" 
                class="form-check-input" 
                id="completado"
                formControlName="completado"
              />
              <label class="form-check-label" for="completado">
                ✅ Juego completado
              </label>
            </div>

            <!-- Imagen URL -->
            <div class="mb-3">
              <label for="imagen" class="form-label">URL de la Imagen</label>
              <div class="d-flex align-items-center gap-3">
                <input 
                  type="url" 
                  class="form-control" 
                  id="imagen"
                  formControlName="imagen"
                  placeholder="https://..."
                />
                <div style="width:80px;height:80px;border:1px solid #ddd;border-radius:6px;overflow:hidden;background:#f8f9fa;">
                  <a *ngIf="previewUrl" [href]="previewUrl" target="_blank" rel="noreferrer">
                    <img [src]="previewUrl" alt="preview" style="width:100%;height:100%;object-fit:cover;" (error)="previewError=true" (load)="previewError=false" />
                  </a>
                  <div *ngIf="!previewUrl" class="text-center text-muted" style="font-size:12px;padding-top:26px;">Previsual.</div>
                  <div *ngIf="previewError" class="text-center text-muted" style="font-size:10px;padding:6px;">URL inválida</div>
                </div>
              </div>
            </div>

            <!-- Botones -->
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
              <button type="button" class="btn btn-secondary" (click)="cancelar()">
                ❌ Cancelar
              </button>
              <button type="submit" class="btn btn-primary" [disabled]="formulario.invalid || cargando">
                💾 {{ editando ? 'Actualizar' : 'Crear' }}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
