// frontend-react/src/App.jsx
import React from 'react';
import { BrowserRouter as Router, Routes, Route, useNavigate } from 'react-router-dom';
import ListaJuegos from './components/ListaJuegos/ListaJuegos';
import DetalleJuego from './components/DetalleJuego/DetalleJuego';
import FormularioJuego from './components/FormularioJuego/FormularioJuego';
import './App.css';

const NavBar = () => {
  const navigate = useNavigate();

  return (
    <nav className="navbar navbar-dark bg-dark" style={{ position: 'sticky', top: 0, zIndex: 1020 }}>
      <div className="container-fluid">
        <button
          className="navbar-brand"
          onClick={() => navigate('/lista')}
          style={{ border: 'none', background: 'none', cursor: 'pointer' }}
        >
          <span className="fs-4">🎮 GameVault</span>
        </button>
        <span className="navbar-text text-light">Gestor de Videojuegos</span>
      </div>
    </nav>
  );
};

const Footer = () => {
  return (
    <footer className="bg-dark text-light text-center py-4 mt-5">
      <p className="mb-1">&copy; 2026 GameVault - Fase 3 Frontend React</p>
      <p className="mb-0">Conectando con API Backend en puerto 3000</p>
    </footer>
  );
};

const AppContent = () => {
  return (
    <>
      <NavBar />
      <main className="py-4">
        <Routes>
          <Route path="/" element={<ListaJuegos />} />
          <Route path="/lista" element={<ListaJuegos />} />
          <Route path="/crear" element={<FormularioJuego />} />
          <Route path="/editar/:id" element={<FormularioJuego />} />
          <Route path="/detalle/:id" element={<DetalleJuego />} />
          <Route path="*" element={<ListaJuegos />} />
        </Routes>
      </main>
      <Footer />
    </>
  );
};

function App() {
  return (
    <Router>
      <AppContent />
    </Router>
  );
}

export default App;

// frontend-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'GameVault';

  constructor(private router: Router) { }

  irAlInicio(): void {
    this.router.navigate(['/lista']);
  }
}

<nav class="navbar navbar-dark bg-dark" sticky-top>
  <div class="container-fluid">
    <button class="navbar-brand" (click)="irAlInicio()" style="border: none; background: none; cursor: pointer;">
      <span class="fs-4">🎮 GameVault</span>
    </button>
    <span class="navbar-text text-light">Gestor de Videojuegos</span>
  </div>
</nav>

<main class="py-4">
  <router-outlet></router-outlet>
</main>

<footer class="bg-dark text-light text-center py-4 mt-5">
  <p class="mb-1">&copy; 2026 GameVault - Fase 2 Frontend Angular</p>
  <p class="mb-0">Conectando con API Backend en puerto 3000</p>
</footer>
